BinPacking3D-v0:
  normalize: true
  n_envs: 128
  n_timesteps: !!float 2e8
  policy: 'MultiInputPolicy'
  batch_size: 2048
  n_steps: 2048
  gamma: 0.99
  learning_rate: !!float 3e-4
  ent_coef: 0.01
  clip_range: 0.2
  n_epochs: 20
  gae_lambda: 0.95
  max_grad_norm: 0.5
  vf_coef: 0.5
  policy_kwargs: "dict(
                    net_arch=dict(pi=[512, 512, 256], vf=[512, 512, 256])
                  )"